### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by yougotborked** [sameersbn/docker-redis#21]
Redis is up to version 6? any chance for an upgrade to this image?

**Comment by asoluter** [comment]
@yougotborked Actually, you can just use the official redis images and get the same functionality right now. Not sure if it was the case at the time of creation of this repo.

**Comment by yougotborked** [comment]
Since I not exactly a redis expert, I was concerned about upgrading from 4->6 and what impact that might have on my system. I think my use case of using it with his gitlab containers is probably common.

I guess by providing an updated container I was hoping Sameer would consider his current users and let us know if an upgrade was even possible.

I did look into the official one, but I am unsure on how to switch.
Does the official persistent /data map exactly to this container's /var/lib/redis?

**Comment by asoluter** [comment]
@yougotborked Yes, I had no issues with remapping `/var/lib/redis` to `/data`

**Comment by yougotborked** [comment]
Thanks, I was finally able to swap my docker-compose file. worked as expected with the above info.
