### ISSUE TITLE
*** FATAL CONFIG FILE ERROR ***

### ISSUE THREAD

**Issue by BerndDoser** [sameersbn/docker-redis#3]
Building the latest commit using

    docker build -t redis .

and printing the version of redis

    docker run redis redis-server --version

I get following error message:

    Starting redis-server...
    *** FATAL CONFIG FILE ERROR ***
    Reading the configuration file, at line 709
    >>> 'version'
    Bad directive or wrong number of arguments

**Comment by sameersbn** [comment]
@BerndDoser The image automatically adds `/etc/redis/redis.conf` to the `redis-server` arguments list. But `redis-server` does not like arguments such as `--version` or `--help` specified after the `redis.conf`, for example,

This is ok:

```bash
redis-server --help /etc/redis/redis.conf
```

This is not ok.

```bash
redis-server /etc/redis/redis.conf --help
```

The solution to this issue would appear to specify `/etc/redis/redis.conf` at the end of the argument list. But this causes issues on the other side as well, eg.

This is ok:

```bash
redis-server /etc/redis/redis.conf --loglevel verbose
```

This is not ok:

```bash
redis-server --loglevel verbose /etc/redis/redis.conf
```

So to remedy this issue, the image will no longer add `/etc/redis/redis.conf` to the argument list when user specifies the `redis-server` command.

This will work:

```bash
docker run -it --rm sameersbn/redis redis-server --help
```

This will not:

```bash
docker run -it --rm sameersbn/redis --help
```

**Comment by BerndDoser** [comment]
Thanks for your very fast solution!
